# Generated by Django 5.1.3 on 2025-05-15 20:17

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
