# Generated by Django 5.1.3 on 2025-05-12 02:33

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('blogapp', 'Category')
    categories = ['Razas', 'Pelajes', 'Moods', 'Colores']
    for name in categories:
        Category.objects.create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_category_alter_blog_content_alter_review_rating_and_more'),
    ]

    operations = []
