# Generated by Django 5.1.3 on 2025-05-12 03:06

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('blogapp', 'Category')
    categories = ['Razas', 'Pelajes', 'Moods', 'Colores']
    for name in categories:
        Category.objects.create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0004_auto_20250511_2133"),
    ]

    operations = []
